Pevtsov Task2
sergey-berezin/401_pevczov pull request #2
Opened 2024-10-24 20:02 UTC by Tun-0-Tun

2024-10-24 20:03 UTC, Tun-0-Tun commented
Task2 code

2024-10-29 07:50 UTC, sergey-berezin requested changes

2024-10-29 07:50 UTC, sergey-berezin commented on wpfStadium/MainWindow.xaml.cs
> +                        for (int n = 0; n < N; n++)
Необходимо сделать выдачу расписание турнира в виде таблицы. Можно использовать `TextBlock` внутри `ScrollView` или многострочный `TextBox` с моноширинным шрифтом.

2024-10-29 07:50 UTC, sergey-berezin commented on TournamentScheduler/Scheduler.cs
> +                lock (lockObj)
Вместо списка с `lock` лучше использовать прямую запись в элемент массива.

2024-11-08 09:35 UTC, merged